services:
  marketplace:
    ports:
     - 8080:8080
    build:
     context: ./server
     dockerfile: ./Dockerfile
    volumes:
     - ./server/resources:/resources
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
  
  postgres:
    image: postgres:13.3
    ports:
     - 5432:5432
    # volumes:
    #  - ./psql_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: psql
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d psql" ]
      interval: 30s
      timeout: 30s
      retries: 5

  migrate:
    image: migrate/migrate
    volumes:
     - ./server/repository/postgres/migrations:/migrations
    command:
      [ "-path", 
      "/migrations", 
      "-database", 
      "postgres://user:password@postgres:5432/psql?sslmode=disable", "up" ]
    depends_on:
      postgres:
        condition: service_healthy
